name: chat_list
description: A flutter package to incorporate a chat view in a simple way
version: 2.0.0
homepage: "https://github.com/lapadev/chat-list-flutter-package"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bubble: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


